export const MOCK_DATA: any[] = [
    // MAR '26
    {
        id: '1',
        vendor: 'Urban Company',
        amount: 2374.00,
        dateStr: '28th mar 8:09 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'urban',
    },
    {
        id: '2',
        vendor: 'Mygate',
        amount: 10002.36,
        dateStr: '25th mar 11:37 pm',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'mygate',
    },
    {
        id: '3',
        vendor: 'Chai La Tandoor Chai',
        amount: 135.00,
        dateStr: '19th mar 1:26 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'chai',
    },
    {
        id: '4',
        vendor: 'Vijay Auto Service',
        amount: 57.00,
        dateStr: '18th mar 10:25 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'auto',
    },
    {
        id: '5',
        vendor: 'Blinkit',
        amount: 443.00,
        dateStr: '16th mar 9:05 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '6',
        vendor: 'Blinkit',
        amount: 261.00,
        dateStr: '7th mar 7:42 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '7',
        vendor: 'Blinkit',
        amount: 1291.00,
        dateStr: '7th mar 7:25 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },

    // FEB '26
    {
        id: '8',
        vendor: 'Blinkit',
        amount: 347.00,
        dateStr: '9th feb 8:20 am',
        monthGroup: "FEB '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '9',
        vendor: 'Blinkit',
        amount: 260.00,
        dateStr: '8th feb 11:07 am',
        monthGroup: "FEB '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },

    // JAN '26
    {
        id: '10',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 1:03 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '11',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 1:02 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '12',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 1:02 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '13',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 12:56 am',
        monthGroup: "JAN '26",
        status: 'FAILED',
        iconType: 'education',
    },
    {
        id: '14',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 12:52 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '15',
        vendor: 'Zepto',
        amount: 335.00,
        dateStr: '5th jan 8:40 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'zepto',
    },
    {
        id: '16',
        vendor: 'Education Fees Payment',
        amount: 25200.00,
        dateStr: '2nd jan 12:14 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },

    // DEC '25
    {
        id: '17',
        vendor: 'Blinkit',
        amount: 209.00,
        dateStr: '28th dec 10:57 pm',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '18',
        vendor: 'Swiggy Instamart',
        amount: 288.00,
        dateStr: '28th dec 3:04 pm',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'swiggy',
    },
    {
        id: '19',
        vendor: 'Education Fees Payment',
        amount: 8000.00,
        dateStr: '20th dec 8:33 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '20',
        vendor: 'Education Fees Payment',
        amount: 5600.00,
        dateStr: '20th dec 8:30 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '21',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '20th dec 8:29 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '22',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '19th dec 11:50 pm',
        monthGroup: "DEC '25",
        status: 'FAILED',
        iconType: 'education',
    },

    // NOV '25
    {
        id: '23',
        vendor: 'Education Fees Payment',
        amount: 8000.00,
        dateStr: '26th nov 8:33 pm',
        monthGroup: "NOV '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "26th nov 8:33 PM",
        TransactionAmount: 8000,
        PaymentInitiatedDate: "26th nov",
        PaymentInitiatedTime: "8:33 PM",
        BankConfirmationDate: "26th nov",
        BankConfirmationTime: "8:39 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 8220.0,
        Time: "8:39 PM",
        Date: "26th nov",
        UtrNumber: null,
    },
    {
        id: '24',
        vendor: 'Education Fees Payment',
        amount: 25200.00,
        dateStr: '26th nov 8:32 pm',
        monthGroup: "NOV '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "26th nov 8:32 PM",
        TransactionAmount: 25200,
        PaymentInitiatedDate: "26th nov",
        PaymentInitiatedTime: "8:32 PM",
        BankConfirmationDate: "26th nov",
        BankConfirmationTime: "8:34 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: null,
        Utr: "535423011498",
        TotalAmount: 25893.0,
        Time: "8:34 PM",
        Date: "26th nov",
        UtrNumber: "535423011498",
    },
    {
        id: '25',
        vendor: 'Education Fees Payment',
        amount: 56000.00,
        dateStr: '26th nov 8:28 pm',
        monthGroup: "NOV '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "26th nov 8:28 PM",
        TransactionAmount: 56000,
        PaymentInitiatedDate: "26th nov",
        PaymentInitiatedTime: "8:28 PM",
        BankConfirmationDate: "26th nov",
        BankConfirmationTime: "8:29 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 57540.0,
        Time: "8:29 PM",
        Date: "26th nov",
        UtrNumber: null,
    },

    // OCT '25
    {
        id: '26',
        vendor: 'Education Fees Payment',
        amount: 18000.00,
        dateStr: '28th oct 7:23 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "28th oct 7:23 PM",
        TransactionAmount: 18000,
        PaymentInitiatedDate: "28th oct",
        PaymentInitiatedTime: "7:23 PM",
        BankConfirmationDate: "28th oct",
        BankConfirmationTime: "7:29 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 18495.0,
        Time: "7:29 PM",
        Date: "28th oct",
        UtrNumber: null,
    },
    {
        id: '27',
        vendor: 'Education Fees Payment',
        amount: 27720.00,
        dateStr: '28th oct 7:22 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "28th oct 7:22 PM",
        TransactionAmount: 27720,
        PaymentInitiatedDate: "28th oct",
        PaymentInitiatedTime: "7:22 PM",
        BankConfirmationDate: "28th oct",
        BankConfirmationTime: "7:27 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: null,
        Utr: null,
        TotalAmount: 28482.3,
        Time: "7:27 PM",
        Date: "28th oct",
        UtrNumber: null,
    },
    {
        id: '28',
        vendor: 'Education Fees Payment',
        amount: 28000.00,
        dateStr: '27th oct 10:44 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "27th oct 10:44 PM",
        TransactionAmount: 28000,
        PaymentInitiatedDate: "27th oct",
        PaymentInitiatedTime: "10:44 PM",
        BankConfirmationDate: "27th oct",
        BankConfirmationTime: "10:53 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 28770.0,
        Time: "10:53 PM",
        Date: "27th oct",
        UtrNumber: null,
    },
    {
        id: '29',
        vendor: 'Education Fees Payment',
        amount: 61600.00,
        dateStr: '27th oct 10:37 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "27th oct 10:37 PM",
        TransactionAmount: 61600,
        PaymentInitiatedDate: "27th oct",
        PaymentInitiatedTime: "10:37 PM",
        BankConfirmationDate: "27th oct",
        BankConfirmationTime: "10:40 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 63294.0,
        Time: "10:40 PM",
        Date: "27th oct",
        UtrNumber: null,
    },

    // SEP '25
    {
        id: '30',
        vendor: 'Card Tokenisation',
        amount: 2.00,
        dateStr: '22nd sep 9:20 pm',
        monthGroup: "SEP '25",
        status: 'FAILED',
        iconType: 'card',
        hasSupportAction: true,
    },
    {
        id: '31',
        vendor: 'Education Fees Payment',
        amount: 23600.00,
        dateStr: '21st sep 2:37 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "21st sep 2:37 PM",
        TransactionAmount: 23600,
        PaymentInitiatedDate: "21st sep",
        PaymentInitiatedTime: "2:37 PM",
        BankConfirmationDate: "21st sep",
        BankConfirmationTime: "2:49 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 24249.0,
        Time: "2:49 PM",
        Date: "21st sep",
        UtrNumber: null,
    },
    {
        id: '32',
        vendor: 'Education Fees Payment',
        amount: 16380.00,
        dateStr: '9th sep 1:08 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "9th sep 1:08 PM",
        TransactionAmount: 16380,
        PaymentInitiatedDate: "9th sep",
        PaymentInitiatedTime: "1:08 PM",
        BankConfirmationDate: "9th sep",
        BankConfirmationTime: "1:09 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: null,
        Utr: null,
        TotalAmount: 16830.45,
        Time: "1:09 PM",
        Date: "9th sep",
        UtrNumber: null,
    },
    {
        id: '33',
        vendor: 'Education Fees Payment',
        amount: 32400.00,
        dateStr: '3rd sep 7:40 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "3rd sep 7:40 PM",
        TransactionAmount: 32400,
        PaymentInitiatedDate: "3rd sep",
        PaymentInitiatedTime: "7:40 PM",
        BankConfirmationDate: "3rd sep",
        BankConfirmationTime: "7:44 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: null,
        Utr: null,
        TotalAmount: 33291.0,
        Time: "7:44 PM",
        Date: "3rd sep",
        UtrNumber: null
    },

    // AUG '25
    {
        id: '34',
        vendor: 'Rent Payment',
        amount: 1260.00,
        dateStr: '19th aug 8:44 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'rent',
    },
    {
        id: '35',
        vendor: 'Rent Payment',
        amount: 1260.00,
        dateStr: '18th aug 9:12 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'rent',
    },
    {
        id: '36',
        vendor: 'Rent Payment',
        amount: 12000.00,
        dateStr: '14th aug 8:29 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'rent',
    },
    {
        id: '37',
        vendor: 'Education Fees Payment',
        amount: 4000.00,
        dateStr: '13th aug 11:59 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '38',
        vendor: 'Education Fees Payment',
        amount: 1200.00,
        dateStr: '12th aug 11:58 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '39',
        vendor: 'Education Fees Payment',
        amount: 1200.00,
        dateStr: '12th aug 11:57 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '40',
        vendor: 'Education Fees Payment',
        amount: 1200.00,
        dateStr: '12th aug 6:34 pm',
        monthGroup: "AUG '25",
        status: 'FAILED',
        iconType: 'education',
    },

    // JUL '25
    {
        id: '41',
        vendor: 'Education Fees Payment',
        amount: 4000.00,
        dateStr: '21st jul 1:05 pm',
        monthGroup: "JUL '25",
        status: 'FAILED',
        iconType: 'education',
    },
    {
        id: '42',
        vendor: 'Education Fees Payment',
        amount: 4000.00,
        dateStr: '21st jul 1:00 pm',
        monthGroup: "JUL '25",
        status: 'COMPLETED',
        iconType: 'education',
    },

    // JUN '25
    {
        id: '43',
        vendor: 'Zomato',
        amount: 263.39,
        dateStr: '4th jun 8:36 pm',
        monthGroup: "JUN '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '44',
        vendor: 'Zomato',
        amount: 263.39,
        dateStr: '3rd jun 6:13 pm',
        monthGroup: "JUN '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '45',
        vendor: 'Zomato',
        amount: 224.95,
        dateStr: '1st jun 6:55 pm',
        monthGroup: "JUN '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },

    // FEB '25
    {
        id: '46',
        vendor: 'Zepto',
        amount: 213.15,
        dateStr: '28th feb 2:04 am',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zepto',
    },
    {
        id: '47',
        vendor: 'Zomato',
        amount: 402.40,
        dateStr: '22nd feb 10:28 pm',
        monthGroup: "FEB '25",
        status: 'FAILED',
        hasSupportAction: true,
        iconType: 'zomato',
    },
    {
        id: '48',
        vendor: 'Zomato',
        amount: 402.40,
        dateStr: '17th feb 10:25 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '49',
        vendor: 'Zomato',
        amount: 402.40,
        dateStr: '17th feb 12:37 am',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '50',
        vendor: 'Zomato',
        amount: 295.90,
        dateStr: '16th feb 11:42 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '51',
        vendor: 'Zomato',
        amount: 321.79,
        dateStr: '16th feb 4:29 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '52',
        vendor: 'Zomato',
        amount: 416.50,
        dateStr: '15th feb 7:03 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '53',
        vendor: 'Zomato',
        amount: 647.05,
        dateStr: '15th feb 1:50 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    }
];