export const MOCK_DATA: any[] = [
    // MAR '26
    {
        id: '1',
        vendor: 'Urban Company',
        amount: 2374.00,
        dateStr: '28th mar 8:09 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'urban',
    },
    {
        id: '2',
        vendor: 'Mygate',
        amount: 10002.36,
        dateStr: '25th mar 11:37 pm',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'mygate',
    },
    {
        id: '3',
        vendor: 'Chai La Tandoor Chai',
        amount: 135.00,
        dateStr: '19th mar 1:26 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'chai',
    },
    {
        id: '4',
        vendor: 'Vijay Auto Service',
        amount: 57.00,
        dateStr: '18th mar 10:25 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'auto',
    },
    {
        id: '5',
        vendor: 'Blinkit',
        amount: 443.00,
        dateStr: '16th mar 9:05 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '6',
        vendor: 'Blinkit',
        amount: 261.00,
        dateStr: '7th mar 7:42 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '7',
        vendor: 'Blinkit',
        amount: 1291.00,
        dateStr: '7th mar 7:25 am',
        monthGroup: "MAR '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },

    // FEB '26
    {
        id: '8',
        vendor: 'Blinkit',
        amount: 347.00,
        dateStr: '9th feb 8:20 am',
        monthGroup: "FEB '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '9',
        vendor: 'Blinkit',
        amount: 260.00,
        dateStr: '8th feb 11:07 am',
        monthGroup: "FEB '26",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '10',
        vendor: 'Education Fees Payment',
        amount: 27720.00,
        dateStr: '2nd feb 4:49 pm',
        monthGroup: "FEB '26",
        status: 'COMPLETED',
        iconType: 'education',
    },

    // JAN '26
    {
        id: '11',
        vendor: 'Education Fees Payment',
        amount: 5600.00,
        dateStr: '28th jan 3:56 pm',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '12',
        vendor: 'Education Fees Payment',
        amount: 8000.00,
        dateStr: '28th jan 3:55 pm',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '13',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 3:54 pm',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '14',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 1:03 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '15',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 1:02 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '16',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 1:02 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '17',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 12:56 am',
        monthGroup: "JAN '26",
        status: 'FAILED',
        iconType: 'education',
    },
    {
        id: '18',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '28th jan 12:52 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '19',
        vendor: 'Education Fees Payment',
        amount: 33600.00,
        dateStr: '25th jan 8:43 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '20',
        vendor: 'Zepto',
        amount: 335.00,
        dateStr: '5th jan 8:40 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'zepto',
    },
    {
        id: '21',
        vendor: 'Education Fees Payment',
        amount: 25200.00,
        dateStr: '2nd jan 12:14 am',
        monthGroup: "JAN '26",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "02 JAN 12:14 AM",
        TransactionAmount: 25200,
        PaymentInitiatedDate: "2nd jan",
        PaymentInitiatedTime: "12:14 AM",
        BankConfirmationDate: "02 JAN",
        BankConfirmationTime: "12:19 AM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: '01KDXE087RYKCSKWZ0FA8VEFX4-2006339',
        Utr: '600223002590',
        TotalAmount: 25893.0,
        Time: "12:19 AM",
        Date: "2nd jan",
        Both: '02 Jan 26',
        UtrNumber: '600223002590',
        pdf: require('../assets/images/02_Jan_25200.jpg')
    },

    // DEC '25
    {
        id: '22',
        vendor: 'Blinkit',
        amount: 209.00,
        dateStr: '28th dec 10:57 pm',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'blinkit',
    },
    {
        id: '23',
        vendor: 'Swiggy Instamart',
        amount: 288.00,
        dateStr: '28th dec 3:04 pm',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'swiggy',
    },
    {
        id: '24',
        vendor: 'Education Fees Payment',
        amount: 8000.00,
        dateStr: '20th dec 8:33 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '25',
        vendor: 'Education Fees Payment',
        amount: 5600.00,
        dateStr: '20th dec 8:30 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '26',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '20th dec 8:29 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '27',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '20th dec 8:24 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '28',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '20th dec 8:21 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '29',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '20th dec 8:17 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '30',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '20th dec 8:14 am',
        monthGroup: "DEC '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '31',
        vendor: 'Education Fees Payment',
        amount: 8400.00,
        dateStr: '19th dec 11:50 pm',
        monthGroup: "DEC '25",
        status: 'FAILED',
        iconType: 'education',
    },

    // NOV '25
    {
        id: '32',
        vendor: 'Education Fees Payment',
        amount: 8000.00,
        dateStr: '26th nov 08:33 pm',
        monthGroup: "NOV '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "26 NOV 08:33 PM",
        TransactionAmount: 8000,
        PaymentInitiatedDate: "26th nov",
        PaymentInitiatedTime: "08:33 PM",
        BankConfirmationDate: "26 NOV",
        BankConfirmationTime: "08:39 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01KB0B2G53B2SW688HTBEEV16W-2259703',
        Utr: '652984794706',
        TotalAmount: 8220.0,
        Time: "08:39 PM",
        Date: "26th nov",
        Both: '26 Nov 25',
        UtrNumber: '652984794706',
        pdf: require('../assets/images/26_nov_8000.jpg')
    },
    {
        id: '33',
        vendor: 'Education Fees Payment',
        amount: 25200.00,
        dateStr: '26th nov 8:32 pm',
        monthGroup: "NOV '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "26 NOV 08:32 PM",
        TransactionAmount: 25200,
        PaymentInitiatedDate: "26th nov",
        PaymentInitiatedTime: "8:32 PM",
        BankConfirmationDate: "26 NOV",
        BankConfirmationTime: "08:34 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: '01KB0AZ3AEEVMD1N4T5Q3V7Q18-7004312',
        Utr: '533021233027',
        TotalAmount: 25893.0,
        Time: "8:34 PM",
        Date: "26th nov",
        Both: '26 Nov 25',
        UtrNumber: "533021233027",
        pdf: require('../assets/images/26_Nov_25200.jpg')
    },
    {
        id: '34',
        vendor: 'Education Fees Payment',
        amount: 56000.00,
        dateStr: '26th nov 8:28 pm',
        monthGroup: "NOV '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "26 NOV 08:28 PM",
        TransactionAmount: 56000,
        PaymentInitiatedDate: "26th nov",
        PaymentInitiatedTime: "8:28 PM",
        BankConfirmationDate: "26 NOV",
        BankConfirmationTime: "08:29 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01KB0AQY2XKPJXP7G84KCJQCRR-7142882',
        Utr: '495407957833',
        TotalAmount: 57540.0,
        Time: "8:29 PM",
        Date: "26th nov",
        Both: '26 Nov 25',
        UtrNumber: '495407957833',
        pdf: require('../assets/images/26_Nov_56000.jpg')
    },

    // OCT '25
    {
        id: '35',
        vendor: 'Education Fees Payment',
        amount: 18000.00,
        dateStr: '28th oct 7:23 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "28 OCT 07:23 PM",
        TransactionAmount: 18000,
        PaymentInitiatedDate: "28th oct",
        PaymentInitiatedTime: "7:23 PM",
        BankConfirmationDate: "28 OCT",
        BankConfirmationTime: "07:26 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01K8NHHKZN25HEY6CFAZEFAS85-4624684',
        Utr: '604306203015',
        TotalAmount: 18495.0,
        Time: "7:26 PM",
        Date: "28th oct",
        Both: '28 Oct 25',
        UtrNumber: '604306203015',
        pdf: require('../assets/images/28_Oct_18000.jpg')
    },
    {
        id: '36',
        vendor: 'Education Fees Payment',
        amount: 27720.00,
        dateStr: '28th oct 7:22 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "28 OCT 07:22 PM",
        TransactionAmount: 27720,
        PaymentInitiatedDate: "28th oct",
        PaymentInitiatedTime: "7:22 PM",
        BankConfirmationDate: "28 OCT",
        BankConfirmationTime: "07:27 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: '01K8NHE8MDDRW8V2NNGFT7W2D-6305186',
        Utr: '62071849165',
        TotalAmount: 28482.30,
        Time: "7:27 PM",
        Date: "28th oct",
        Both: '28 Oct 25',
        UtrNumber: '62071849165',
        pdf: require('../assets/images/28_Oct_27720.jpg')
    },
    {
        id: '37',
        vendor: 'Education Fees Payment',
        amount: 28000.00,
        dateStr: '27th oct 10:44 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "27 OCT 10:44 PM",
        TransactionAmount: 28000,
        PaymentInitiatedDate: "27th oct",
        PaymentInitiatedTime: "10:44 PM",
        BankConfirmationDate: "27 OCT",
        BankConfirmationTime: "10:53 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01K8KAKK2S02SC6ANDEJC28BG1-9049439',
        Utr: '472673773005',
        TotalAmount: 28770.0,
        Time: "10:53 PM",
        Date: "27th oct",
        Both: '27 Oct 25',
        UtrNumber: '472673773005',
        pdf: require('../assets/images/27_Oct_28000.jpg')
    },
    {
        id: '38',
        vendor: 'Education Fees Payment',
        amount: 61600.00,
        dateStr: '27th oct 10:37 pm',
        monthGroup: "OCT '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "27 OCT 10:37 PM",
        TransactionAmount: 61600,
        PaymentInitiatedDate: "27th oct",
        PaymentInitiatedTime: "10:37 PM",
        BankConfirmationDate: "27 OCT",
        BankConfirmationTime: "10:40 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01K8KA7Q2AM54CPHGEBZXCGNGD-6771792',
        Utr: '510784016497',
        TotalAmount: 63294.0,
        Time: "10:40 PM",
        Date: "27th oct",
        Both: '27 Oct 25',
        UtrNumber: '510784016497',
        pdf: require('../assets/images/27_Oct_61600.jpg')
    },

    // SEP '25
    {
        id: '39',
        vendor: 'Education Fees Payment',
        amount: 12000.00,
        dateStr: '28th sep 4:32 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "28 SEP 04:32 PM",
        TransactionAmount: 12000,
        PaymentInitiatedDate: "28th sep",
        PaymentInitiatedTime: "4:32 PM",
        BankConfirmationDate: "28 SEP",
        BankConfirmationTime: "04:40 PM",
        AmountDepositedToUpiId: "shimanshu.mathur@okicici",
        TutorName: "Shimanshu Mathur",
        OrderId: '01KCKQR9MQEQR3B5PAMQY9L0A-5023042',
        Utr: '601946567097',
        TotalAmount: 12330.0,
        Time: "4:40 PM",
        Date: "28th sep",
        Both: '28 Sep 25',
        UtrNumber: '601946567097',
        pdf: null
    },
    {
        id: '40',
        vendor: 'Rent Payment',
        amount: 25200.00,
        dateStr: '22nd sep 10:06 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'rent',
        TransactionDate: "22 SEP 10:06 PM",
        TransactionAmount: 25200,
        PaymentInitiatedDate: "22nd sep",
        PaymentInitiatedTime: "10:06 PM",
        BankConfirmationDate: "22 SEP",
        BankConfirmationTime: "10:08 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: '01K2YXGPPXFE4S4Y9TEKBA0WFX-6231456',
        Utr: '605127742655',
        TotalAmount: 25893.0,
        Time: "10:08 PM",
        Date: "22nd sep",
        Both: '22 Sep 25',
        UtrNumber: '605127742655',
        pdf: require('../assets/images/22_Sep_25200.jpg')

    },
    {
        id: '41',
        vendor: 'Education Fees Payment',
        amount: 23600.00,
        dateStr: '21st sep 2:37 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "21 SEP 02:37 PM",
        TransactionAmount: 23600,
        PaymentInitiatedDate: "21st sep",
        PaymentInitiatedTime: "2:37 PM",
        BankConfirmationDate: "21 SEP",
        BankConfirmationTime: "02:49 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01K5S4J63GC5V33H5Z25Y8FCYD-3587006',
        Utr: '410596112645',
        TotalAmount: 24249.0,
        Time: "2:49 PM",
        Date: "21st sep",
        Both: '21 Sep 25',
        UtrNumber: '410596112645',
        pdf: require('../assets/images/21_Sep_23600.jpg')
    },
    {
        id: '42',
        vendor: 'Education Fees Payment',
        amount: 16380.00,
        dateStr: '9th sep 1:08 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "09 SEP 01:08 PM",
        TransactionAmount: 16380,
        PaymentInitiatedDate: "9th sep",
        PaymentInitiatedTime: "1:08 PM",
        BankConfirmationDate: "09 SEP",
        BankConfirmationTime: "01:11 PM",
        AmountDepositedToUpiId: "Q032832151@ybl",
        TutorName: "24 VISION HOSPITALITY PRIVATE LIMITED",
        OrderId: '01K4PPK4Y4R73YA7BBJ6QXV8JS-2453260',
        Utr: '430423052525',
        TotalAmount: 16830.45,
        Time: "1:11 PM",
        Date: "9th sep",
        Both: '09 Sep 25',
        UtrNumber: '430423052525',
        pdf: require('../assets/images/09_Sep_16380.jpg')
    },
    {
        id: '43',
        vendor: 'Education Fees Payment',
        amount: 32400.00,
        dateStr: '3rd sep 7:40 pm',
        monthGroup: "SEP '25",
        status: 'COMPLETED',
        iconType: 'education',
        TransactionDate: "03 SEP 07:40 PM",
        TransactionAmount: 32400,
        PaymentInitiatedDate: "3rd sep",
        PaymentInitiatedTime: "7:40 PM",
        BankConfirmationDate: "03 SEP",
        BankConfirmationTime: "07:43 PM",
        AmountDepositedToUpiId: "saisevataxi-1@oksbi",
        TutorName: "Tanaji Sonaji Nagre",
        OrderId: '01K47YMTWFE8SV6A0V1JV0SKSF-6578720',
        Utr: '562845632465',
        TotalAmount: 33291.0,
        Time: "7:43 PM",
        Date: "3rd sep",
        Both: '03 Sep 25',
        UtrNumber: '562845632465',
        pdf: require('../assets/images/03_Sep_32400.jpg')
    },

    // AUG '25
    {
        id: '44',
        vendor: 'Rent Payment',
        amount: 1260.00,
        dateStr: '19th aug 8:44 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'rent',
    },
    {
        id: '45',
        vendor: 'Rent Payment',
        amount: 1260.00,
        dateStr: '18th aug 9:12 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'rent',
    },
    {
        id: '46',
        vendor: 'Rent Payment',
        amount: 12000.00,
        dateStr: '14th aug 8:29 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'rent',
    },
    {
        id: '47',
        vendor: 'Education Fees Payment',
        amount: 4000.00,
        dateStr: '13th aug 11:59 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '48',
        vendor: 'Education Fees Payment',
        amount: 1200.00,
        dateStr: '12th aug 11:58 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '49',
        vendor: 'Education Fees Payment',
        amount: 1200.00,
        dateStr: '12th aug 11:57 pm',
        monthGroup: "AUG '25",
        status: 'COMPLETED',
        iconType: 'education',
    },
    {
        id: '50',
        vendor: 'Education Fees Payment',
        amount: 1200.00,
        dateStr: '12th aug 6:34 pm',
        monthGroup: "AUG '25",
        status: 'FAILED',
        iconType: 'education',
    },

    // JUL '25
    {
        id: '51',
        vendor: 'Education Fees Payment',
        amount: 4000.00,
        dateStr: '21st jul 1:05 pm',
        monthGroup: "JUL '25",
        status: 'FAILED',
        iconType: 'education',
    },
    {
        id: '52',
        vendor: 'Education Fees Payment',
        amount: 4000.00,
        dateStr: '21st jul 1:00 pm',
        monthGroup: "JUL '25",
        status: 'COMPLETED',
        iconType: 'education',
    },

    // JUN '25
    {
        id: '53',
        vendor: 'Zomato',
        amount: 263.39,
        dateStr: '4th jun 8:36 pm',
        monthGroup: "JUN '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '54',
        vendor: 'Zomato',
        amount: 263.39,
        dateStr: '3rd jun 6:13 pm',
        monthGroup: "JUN '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '55',
        vendor: 'Zomato',
        amount: 224.95,
        dateStr: '1st jun 6:55 pm',
        monthGroup: "JUN '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },

    // FEB '25
    {
        id: '56',
        vendor: 'Zepto',
        amount: 213.15,
        dateStr: '28th feb 2:04 am',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zepto',
    },
    {
        id: '57',
        vendor: 'Zomato',
        amount: 402.40,
        dateStr: '22nd feb 10:28 pm',
        monthGroup: "FEB '25",
        status: 'FAILED',
        hasSupportAction: true,
        iconType: 'zomato',
    },
    {
        id: '58',
        vendor: 'Zomato',
        amount: 402.40,
        dateStr: '17th feb 10:25 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '59',
        vendor: 'Zomato',
        amount: 402.40,
        dateStr: '17th feb 12:37 am',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '60',
        vendor: 'Zomato',
        amount: 295.90,
        dateStr: '16th feb 11:42 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '61',
        vendor: 'Zomato',
        amount: 321.79,
        dateStr: '16th feb 4:29 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '62',
        vendor: 'Zomato',
        amount: 416.50,
        dateStr: '15th feb 7:03 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    },
    {
        id: '63',
        vendor: 'Zomato',
        amount: 647.05,
        dateStr: '15th feb 1:50 pm',
        monthGroup: "FEB '25",
        status: 'COMPLETED',
        iconType: 'zomato',
    }
];